### ISSUE TITLE
Import files into scitos

### ISSUE THREAD

**Issue by Ltah72** [scientific-tool-set/scitos#27]
Hi Carsten, 

My name is Lenore, and I and other members from Donna Rose Addis and Lynette Tippett's lab are using your program for AI coding at the University of Auckland. 

I was wondering if there is any way that files can be imported into scitos? For example, we typically store the raw interviews in word or excel files, where we would then have to manually copy and paste them into scitos to begin the coding. I was wondering if there was a feature in scitos that would allow a more automatic process to easily transfer the files into scitos?

**Comment by CarstenWickner** [comment]
Hi Lenore,

Great to you hear you are still using it since we created the AI scoring tool specifically for you guys a couple of years ago. 😄

As to the import feature, no such things exists currently.
But that doesn't mean it can't be added. I'd just need to understand a bit more what it is you are after exactly.
- Back in 2015, the process was already that you received the raw interviews as an MS Word document. The fact that you'd have to copy it all and then paste it into SciToS was deemed acceptable back then since it boils down to only three keyboard short-cuts (`Ctrl + A`/`Ctrl + C`/`Ctrl + V`). Is there maybe more to it now or is that still as "simple" for an MS Word document?
- What would the file structure in the case of an MS Excel document be? Does that include multiple interviews then (as separate worksheets or parallel columns in one worksheet)?

Maybe you can describe what you'd deem the ideal process in using the tool to be and I can try to make it work like that. 😉

**Comment by Ltah72** [comment]
Thanks for the quick response! 

I'm just using simple word/excel file 😃 So, for example, with excel, there's one column for the trial ID, and one column for the transcription. Each excel row contains a different trial. And so, I want each trial to be a new and individual interview in scitos.

**Comment by CarstenWickner** [comment]
Hi Lenore,

I'm happy to let you know: there is a new version of SciToS now: [v2.3.0](https://github.com/scientific-tool-set/scitos/releases/tag/v2.3.0)
This includes a technical update under the hood, now requiring Java 8 as minimum version (which I assume is fine, since even that Java version is almost out of official support because it is so old 😉).

But noteworthy for you: this new version also includes the possibility of importing a bunch of interviews at once from an ODS (Open Document Standard) Spreadsheet.
To that end, you can find a new entry in the "Edit" menu while looking at an open AIS project:
- "Edit" > "Import Interviews (from Spreadsheet)"

Selecting this menu item will ask you to select the spreadsheet file. If that is a valid ODS spreadsheet, a dialog will be shown that will ask you to select the particular worksheet to import from and for that also which column contains the participant ids and which column contains the transcribed interview text.
In a preview table, you can then select those interviews you want to import and you're good to go.

**Comment by Ltah72** [comment]
Hi Carsten, 

Thanks so much for this :) However, it's not working for me :(  I see the option to import files from the menu, and when I try and import the files, it allows me to select a file, but after that, nothing happens. Does the spreadsheet need to have a certain format to work? I have it as column 1 for participant ID and column 2 as participant response. I've attached a sample.
 
[sample.xlsx](https://github.com/scientific-tool-set/scitos/files/4308482/sample.xlsx)

**Comment by CarstenWickner** [comment]
Hi Lenore,

As per above comment, It's expecting an `.ods` (OpenDocument Spreadsheet) file.
In MS Excel, you can use the "Save As" option and select "OpenDocument Spreadsheet (*.ods)". In my version of MS Excel, that's the very last option at the bottom of the list.

**Comment by CarstenWickner** [comment]
Hi Lenore,

I've improved the error handling now so SciToS (as of version [v2.3.1](https://github.com/scientific-tool-set/scitos/releases/tag/v2.3.1)) will now tell you more explicitly that it wants an `*.ods` file. 😉
I also fixed an issue related to an `*.ods` file containing empty sheets, like your given example (after conversion):
[sample.ods.zip](https://github.com/scientific-tool-set/scitos/files/4309103/sample.ods.zip)

**Comment by Ltah72** [comment]
Works brilliantly! No need to use excel -- ods is fine :) 

I'll pass this on to our other lab members at UOA. We'll be sure to credit you as well!  :) Thank you so much again 😄

**Comment by Ltah72** [comment]
Also, just for reference, is it pronounced 'sye - tose' or 'skee - tose', or something else?

**Comment by CarstenWickner** [comment]
It’s short for “Scientific Tool Set”.
I pronounce it like “sigh-toss”, but you can call it what you want. 😅
